## Reference: https://github.com/helm/chart-testing-action
name: Lint
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened]


jobs:
  chart-test:
    name: Helm Template
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.1
      - name: Dependency build
        run: helm dependency build ./charts/testkube

      - name: helm-check
        uses: igabaydulin/helm-check-action@0.2.0
        env:
          CHART_LOCATION: ./charts/testkube



